{{- if .Values.web.ingress.traefik.enabled }}
{{- $fullName := include "jitsi-meet.name-web" . -}}
{{- $svcPort := .Values.web.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
{{ include "jitsi-meet.labels" . | indent 4 }}
  annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
      traefik.ingress.kubernetes.io/router.entrypoints: websecure 
spec:
  entryPoints:
    - {{ .Values.web.ingress.traefik.entry_point }}
  routes:
  - match: Host(`{{ .Values.web.ingress.traefik.host }}`)  
    kind: Rule
    services:
    - kind: Service
      name: {{ $fullName }}
      port: {{ $svcPort }}
      passHostHeader: true
      scheme: http
  tls:  
    secretName: {{ .Values.web.ingress.traefik.tls_secret_name }} 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.web.ingress.traefik.tls_secret_name }}   
spec:
  commonName: {{ .Values.web.ingress.traefik.host }}
  secretName: {{ .Values.web.ingress.traefik.tls_secret_name }}   
  dnsNames:
    - {{ .Values.web.ingress.traefik.host }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}